packages:
  - packages/*

catalogs:
  eslint:
    "@eslint/eslintrc": 2.1.0
    "@hono/eslint-config": 2.0.3
    "@typescript-eslint/parser": 8.46.1
    eslint: 9.38.0
    eslint-config-next: 15.5.6
    eslint-config-prettier: 10.1.8
    typescript-eslint: 8.46.1
  prettier:
    prettier: 3.6.2
    prettier-plugin-tailwindcss: 0.7.1
  tsconfig:
    "@tsconfig/node-ts": 23.6.1
    "@tsconfig/node24": 24.0.1
    "@types/node": 24.8.1
  typescript:
    typescript: 5.9.3

onlyBuiltDependencies:
  - lefthook
  - unrs-resolver

publicHoistPattern:
  - "*eslint*"
